#IP COMPUTERS YOU WANT TO CONNECT TO
ips = ['localhost', 'localhost']

#DISKS OF COMPUTERS YOU WANT TO CONNECT TO (DISKS MUST MATCH THE COMPUTER NUMBER)
ipsdisk = ['E:', 'C:']

#PORTS OF COMPUTERS YOU WANT TO CONNECT TO
ipsport = [4445, 4444]